name: nextflow-env
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::python
- conda-forge::pandas
- conda-forge::numpy
- bioconda::ensembl-vep
- conda-forge::cython
- gxx
- setuptools
- scipy
- wheel
- pip
- pip:
    - inmoose


